### ISSUE TITLE
Resource leak when using ConnectionPolicy.Default

### ISSUE THREAD

**Issue by rytmis** [Azure/azure-documentdb-dotnet#164]
Hi,

This might be a bit off base, but it looks like using DocumentClient with ConnectionPolicy.Default will result in a resource leak that is a bit unavoidable: DocumentClient constructs a GlobalEndpointManager that subscribes to the PreferenceChanged event handler in the ConnectionPolicy and also holds a reference to the DocumentClient and everything in it. 

Unless I'm mistaken, this means that every DocumentClient that uses ConnectionPolicy.Default will hang around indefinitely, and the only way around this is to manage the Connection Policy and its lifetime manually.

Here's a WinDBG/SOS trace of the GC root of a DocumentClient.

```
    0000000000e71700 (pinned handle)
    -> 0000000012172198 System.Object[]
    -> 0000000006ac2c08 Microsoft.Azure.Documents.Client.ConnectionPolicy
    -> 0000000006ac2db0 System.Collections.ObjectModel.ObservableCollection`1[[System.String, mscorlib]]
    -> 000000006636f8b0 System.Collections.Specialized.NotifyCollectionChangedEventHandler
    -> 0000000015c37888 System.Object[]
    -> 000000005c4e7cc0 System.Collections.Specialized.NotifyCollectionChangedEventHandler
    -> 000000005c4e7bf0 Microsoft.Azure.Documents.Routing.GlobalEndpointManager
    -> 000000005c4e7a28 Microsoft.Azure.Documents.Client.DocumentClient
```

Am I missing something obvious?

**Comment by mingaliu** [comment]
Hi rytmis, 
     Thanks for reporting.  Yes, that is a bug.  We will fix it in next SDK release.

**Comment by rytmis** [comment]
For anyone else running into the same issue: the recommendation is to cache and reuse instances of the client (per https://msdn.microsoft.com/library/azure/microsoft.azure.documents.client.documentclient.aspx#Anchor_6 ) -- we were not aware of this, so we ended up exacerbating the issue quite a bit

**Comment by rnagpal** [comment]
This has been fixed on our side and will be included in the next major update to the SDK. Note that as long as you are using a single instance of DocumentClient, you should be good. This becomes an issue if you use a new instance of DocumentClient for every request which will result in host of other issues(performance degradation, port exhaustion, etc.) which we anyways don't recommend. You should have a singleton instance of DocumentClient per app-domain of your application

**Comment by rnagpal** [comment]
@rytmis This is fixed in 1.12.1 release of the SDK. Thanks for reporting it!

**Comment by chadbert** [comment]
This is still occurring in version 1.22.0
Here is an example after a while where there are 2015 registered event handlers. The resources/memory for each connection stays around even though most of them are now closed.
 
![connectionpolicyissue](https://user-images.githubusercontent.com/20522587/46169617-83404680-c250-11e8-8ff3-e2615e48b4e9.png)

Can you deep copy the default ConnectionPolicy instead of just referencing the static instance? There may be more resources that are not getting cleaned up properly. 

Valid use case example:
You are multi-tenant but allow each tenant to own their data. You establish a connection to each tenant's CosmosDb instance and allow each tenant to specify a preferred location. You still use the default policy but just add the preferred location for each connection. Is this going to set the preferred location for all connections to the same value?
