### ISSUE TITLE
Error occurs while reading manually added entries from Cosmos DB Table Storage

### ISSUE THREAD

**Issue by rboorgapally** [Azure/azure-documentdb-dotnet#304]
I have added an entry in the cosmos db from the data explorer available on the portal.
When I tried to read the entry using Azure Premium Storage SDK, I get the following error.

The following is my code. It tries to read all the Key Value entries that have the same partition key. 
```
TableQuery <MyEntity> rangeQuery = new TableQuery<MyEntity>().Where(
                            TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, section.Name));
```
And I get the following exception.
```
"Message": "An error occurred: System.FormatException: Expecting type marker but found 'String'
       at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.ThrowFormatException(String format, Object[] args) in f:\_Bld\14958\10329\Sources\Product\Microsoft.Azure.Documents\Interop\Common\Schema\Edm\TableEntityReader.cs:line 430
       at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.ParseEdmType() in f:\_Bld\14958\10329\Sources\Product\Microsoft.Azure.Documents\Interop\Common\Schema\Edm\TableEntityReader.cs:line 301
       at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.MoveNext() in f:\_Bld\14958\10329\Sources\Product\Microsoft.Azure.Documents\Interop\Common\Schema\Edm\TableEntityReader.cs:line 145
       at Microsoft.WindowsAzure.Storage.Table.Extensions.EntityHelpers.GetProperties(IList`1 selectColumns, String serializedDocument, IDictionary`2& entityProperties, IDictionary`2& documentDBProperties) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\EntityHelpers.cs:line 244
       at Microsoft.WindowsAzure.Storage.Table.Extensions.EntityHelpers.GetEntityPropertiesFromDocument(Document document, TableRequestOptions requestOptions, IList`1 selectColumns) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\EntityHelpers.cs:line 228
       at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionQueryHelper.<QueryDocumentsAsync>d__a`1.MoveNext() in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionQueryHelper.cs:line 118
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionRetryPolicy.<ExecuteUnderRetryPolicy>d__0`1.MoveNext() in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionRetryPolicy.cs:line 0
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionExecutor.ExecuteQuerySegmented[TResult,TInput](TableQuery`1 query, TableContinuationToken token, CloudTableClient client, CloudTable table, EntityResolver`1 resolver, TableRequestOptions requestOptions, OperationContext operationContext) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionExecutor.cs:line 94
       at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.ExecuteQuerySegmentedInternal(TableContinuationToken token, CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\ClassLibraryCommon\Table\TableQuery.cs:line 449
       at Microsoft.WindowsAzure.Storage.Table.TableQuery`1.<>c__DisplayClass7.<ExecuteInternal>b__6(IContinuationToken continuationToken) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\ClassLibraryCommon\Table\TableQuery.cs:line 431
       at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.<LazyEnumerable>d__0`1.MoveNext() in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\Common\Core\Util\CommonUtility.cs:line 322
```

When I add the same entries programmatically, I don't get any error while reading.

It looks like data explorer doesn't add certain fields while updating from the portal.

**Comment by ealsur** [comment]
Did you create or update the entry in the Portal? Could you share the schema (attribute types) you were working on so we could try to repro it?

**Comment by jonlane** [comment]
I'm having the same issue. I get the following error regardless if I am updating or creating. I cut the object down to 1 field that is Int32. It may be specific to __Type and it being a String when updated by the portal.

`   at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.ThrowFormatException(String format, Object[] args) in f:\_Bld\14958\10329\Sources\Product\Microsoft.Azure.Documents\Interop\Common\Schema\Edm\TableEntityReader.cs:line 430
   at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.ParseEdmType() in f:\_Bld\14958\10329\Sources\Product\Microsoft.Azure.Documents\Interop\Common\Schema\Edm\TableEntityReader.cs:line 301
   at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.MoveNext() in f:\_Bld\14958\10329\Sources\Product\Microsoft.Azure.Documents\Interop\Common\Schema\Edm\TableEntityReader.cs:line 145
   at Microsoft.WindowsAzure.Storage.Table.Extensions.EntityHelpers.GetProperties(IList`1 selectColumns, String serializedDocument, IDictionary`2& entityProperties, IDictionary`2& documentDBProperties) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\EntityHelpers.cs:line 244
   at Microsoft.WindowsAzure.Storage.Table.Extensions.EntityHelpers.GetEntityPropertiesFromDocument(Document document, TableRequestOptions requestOptions, IList`1 selectColumns) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\EntityHelpers.cs:line 228
   at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionQueryHelper.<QueryDocumentsAsync>d__a`1.MoveNext() in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionQueryHelper.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionRetryPolicy.<ExecuteUnderRetryPolicy>d__0`1.MoveNext() in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionRetryPolicy.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionExecutor.EndExecute[TResult](IAsyncResult asyncResult) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionExecutor.cs:line 80
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()`

**Comment by rboorgapally** [comment]
@ealsur 

I created the record programmatically and updated it manually on the data explorer

**Comment by ealsur** [comment]
@rboorgapally @jonlane Fix for the Portal is coming this week, will update once its live.

**Comment by ealsur** [comment]
@rboorgapally @jonlane Sorry for the delay. The Portal has been updated and this issue should be solved now.

**Comment by rboorgapally** [comment]
Thanks. It works for me now.

**Comment by zurcacielos** [comment]
I'm still having the same error with cosmos db table API.
Actually I spent 3 days trying to connect an azure function to a cosmos db table api in C# and VS Code.
Several versions of the framework, core and regular, several versions of packages with incompatible dependencies, several versions of the package manager "dotnet" an "nuget", several versions of the azure functions - 1 and beta, several versions of the azure functions core tools, 1 and 2, and several versions of the former version 1, 32 and 64 bits. Plus several client libraries for cosmos db with different examples on the documentation from which none works for me. The errors are either misleading or I need to know the internals of interoperation in a COM component inside the Azure Kernel.

If anybody knows how to connect an azure function to a cosmos db, and it has a vs code git repository, or any workaround, that information will be greatly appreciated. 

System.FormatException: Expecting type Number but found BeginArray at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.ThrowFormatException(String format, Object[] args) at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.Expect(JsonTokenType type) at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.ParseEdmType() at Microsoft.Azure.Documents.Interop.Common.Schema.Edm.TableEntityReader.MoveNext() at Microsoft.Azure.CosmosDB.Table.EdmConverter.GetPropertiesFromDocument(IList`1 selectColumns, String serializedDocument, IDictionary`2& entityProperties, IDictionary`2& documentDBProperties) at Microsoft.Azure.CosmosDB.Tables.SharedFiles.EntityTranslator.GetEntityPropertiesFromDocument(Document document, IList`1 selectColumns) at Microsoft.Azure.CosmosDB.Table.Extensions.TableExtensionQueryHelper.<QueryDocumentsAsync>d__2`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.CosmosDB.Table.Extensions.TableExtensionRetryPolicy.<ExecuteUnderRetryPolicy>d__1`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.CosmosDB.Table.Extensions.TableExtensionExecutor.ExecuteQuerySegmented[TResult,TInput](TableQuery`1 query, TableContinuationToken token, CloudTableClient client, CloudTable table, EntityResolver`1 resolver, TableRequestOptions requestOptions, OperationContext operationContext) at Microsoft.Azure.CosmosDB.Table.TableQuery`1.ExecuteQuerySegmentedInternal(TableContinuationToken token, CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext) at Microsoft.Azure.CosmosDB.Table.TableQuery`1.<>c__DisplayClass41_0.<ExecuteInternal>b__0(IContinuationToken continuationToken) at Microsoft.Azure.Storage.Core.Util.CommonUtility.<LazyEnumerable>d__14`1.MoveNext() at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType) at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer) at Newtonsoft.Json.JsonConvert.SerializeObject(Object value) at Company.Function.HttpTriggerCSharp7.<Run>d__0.MoveNext()

**Comment by ealsur** [comment]
@zurcacielos Could you create another issue? This one is unrelated and it was an old issue with the Azure Portal's schema when inserting new table rows.

**Comment by zurcacielos** [comment]
@ealsur sure, thanks
