### ISSUE TITLE
Can't resolve Microsoft.Azure.Storage.Common package when pulling down Microsoft.Azure.CosmosDB.Table

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-documentdb-dotnet#385]
![image](https://user-images.githubusercontent.com/1309622/32968591-0e94f946-cb9f-11e7-9a43-2239282a7e76.png)

Inspecting [`Microsoft.Azure.Storage.Common` nuget feed](https://www.nuget.org/packages/Microsoft.Azure.Storage.Common) there's only a pre-released version of the package `8.6.0-preview`.

Further looking at the dependecies for Table API client, is it correct for a GA-ed library to take a dependency on a preview package?...

```
.NETFramework 4.5

Microsoft.Azure.DocumentDB (>= 1.19.0)
Microsoft.Azure.KeyVault.Core (>= 1.0.0)
Microsoft.Azure.Storage.Common (>= 8.6.0-preview) <===
Microsoft.Data.OData (>= 5.8.2)
Microsoft.Data.Services.Client (>= 5.8.2)
Microsoft.OData.Core (>= 7.2.0)
Microsoft.OData.Edm (>= 7.2.0)
Microsoft.Spatial (>= 7.2.0)
Newtonsoft.Json (>= 10.0.2)
```

**Comment by SeanFeldman** [comment]
Tried with VS and package manager console, same problem:
![image](https://user-images.githubusercontent.com/1309622/32969199-653b4140-cba1-11e7-991f-9b3dc085d6e5.png)

**Comment by SeanFeldman** [comment]
Looks like a tooling issue.
If a project is configured to use `packages.config` this issue will manifest itself.
If a project is configured to use `PackageReference`, there's no problem with both legacy project system and the new SDK-style projects.

Opened an issue with NuGet https://github.com/NuGet/Home/issues/6196.

**Comment by SeanFeldman** [comment]
Thinking about it, it's not a good practice to mix GA-ed/production grade libraries and preview/beta dependencies. Will keep this open to address that aspect and let team decide what to do about it (potentially another issue).

**Comment by yaronyg** [comment]
It's something that should be fixed in the not too distant future. In the meantime we have doc'd the issue and the work around - https://docs.microsoft.com/en-us/azure/cosmos-db/table-sdk-dotnet#troubleshooting

**Comment by joshlang** [comment]
Still not fixed.  It's necessary to install using:
Install-Package Microsoft.Azure.CosmosDB.Table -IncludePrerelease

**Comment by oskar-fjeld** [comment]
I'm having issue with the latest 2.1.0 version as it has a dependency towards Microsoft.Azure.Storage.Common (>= 8.6.0-preview && <= 9.0.0.1-preview) but the latest version of that is 9.4.2 and only as old as 9.4.0 is available.

**Comment by krispenner** [comment]
@oskar-fjeld I had a similar problem and it was a result of 2 issues:

1. You must target net47 and not netstandard2.0 to use any of the new Microsoft.Azure.Storage packages which includes the Microsoft.Azure.CosmosDB.Table package.

2. It appears the Microsoft.Azure.CosmosDB.Table package does not play well with any of the other storage packages such as the Microsoft.Azure.Storage.Blob package due to the package version constraints put in place. I had to completely separate them into their own projects.

The screenshot below might help, the top project was my original project that targeted netstandard2.0 with the old WindowsAzure.Storage package. However, after trying to upgrade to the new split up packages, I had to separate them into their own projects which are the bottom two projects shown.

![image](https://user-images.githubusercontent.com/8837910/51948080-0ed30b00-23dc-11e9-8654-9a9514a8792c.png)

I hope that may help you and I hope this all get cleaned up sooner than later. There is very little documentation on all the issues covering this. If I were you, you should just remain on the former WindowsAzure.Storage package, I probably will.

**Comment by oskar-fjeld** [comment]
Well I can't install Microsoft.Azure.CosmosDB.Table into an net4.7 project as the oldest version of Microsoft.Azure.Storage.Common available to me is 9.4.0

**Comment by binkiesjoris** [comment]
The current information on the WindowsAzure.Storage package actually instructs you to install Microsoft.Azure.Storage.Blob and Microsoft.Azure.CosmosDB.Table, which are currently still incompatible due to issue mentioned above by @oskar-fjeld with the dependency conflict (i.e. one relies on a version that the other does not support). 

Its no problem to stay on the old WindowsAzure.Storage package as it'll work for now, but it would seem to me that splitting these packages currently misses value as it is impossible to upgrade if you need to use both. A solution to this issue would be greatly appreciated because using 'outdated' packages feels like a sub optimal solution as well.
